import { PROD_UNIV4_CONTRACTS } from "./base-contract-addresses";

// Part of this file gets autogenerated by wagmi.config.ts

// No biome formatting
export const UNIV4_CONTRACTS = {
  ...PROD_UNIV4_CONTRACTS,

  31337: /* START GENERATED ADDRESSES */{
  "poolManager": "0x0D9BAf34817Fccd3b3068768E5d20542B66424A5",
  "positionManager": "0x1685B7cd1b8F100A147E5f3fECF88D176b3EBB1c",
  "stateView": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
  "quoter": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
  "weth": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  "usdc": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
  "universalRouter": "0xB61598fa7E856D43384A8fcBBAbF2Aa6aa044FfC",
  "v4Router": "0xB61598fa7E856D43384A8fcBBAbF2Aa6aa044FfC"
}/* END GENERATED ADDRESSES */,
};
